2018-02-26T02:29:36.860Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:29:36.861Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:29:37.017Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:29:37.017Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:29:37.174Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_12' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:29:37.174Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_12' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_12' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:29:37.335Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:29:37.335Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:29:37.488Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:29:37.488Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:29:37.649Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:29:37.650Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:29:37.898Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:29:37.899Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:29:38.110Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:29:38.110Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:29:38.322Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:29:38.322Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:30:26.396Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:30:26.396Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:30:26.611Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:30:26.611Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:35:03.392Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:35:03.392Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:35:03.548Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:35:03.548Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:35:03.714Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:35:03.714Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '3' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:35:03.873Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '4' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:35:03.873Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '4' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '4' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:35:04.074Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:35:04.074Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '5' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:43:13.894Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Object with ID 'CA_2' in collection with ID 'Asset:org.decentralized.energy.network.Coins' does not exist)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:43:13.894Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'CA_2' in collection with ID 'Asset:org.decentralized.energy.network.Coins' does not exist)","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: Object with ID 'CA_2' in collection with ID 'Asset:org.decentralized.energy.network.Coins' does not exist)\n    at channel.queryByChaincode.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-02-26T02:43:51.592Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_12' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:43:51.593Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_12' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_12' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:44:07.944Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:44:07.944Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '12' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:44:10.781Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:44:10.782Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-26T02:44:10.983Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-26T02:44:10.984Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
