2018-02-06T08:09:47.720Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:09:47.721Z ERROR   HLFConnection           :queryChainCode()         {"message":"Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))","stack":"Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))\n    at channel.queryByChaincode.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:809:34)\n    at <anonymous>"}$
2018-02-06T08:09:47.721Z ERROR   HLFConnection           :ping()                   {"message":"Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))","stack":"Error: Error trying to ping. Error: Error trying to query business network. Error: chaincode error (status: 500, message: Error: The current identity, with the name 'admin' and the identifier '7d195e0cbc77f47d78f39e21ec879210cdff2f8506d5f326af245563ebfcbb69', must be activated (ACTIVATION_REQUIRED))\n    at _checkRuntimeVersions.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:713:34)\n    at <anonymous>"}$
2018-02-06T08:17:56.379Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:17:56.379Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:24:03.546Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:24:03.546Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:24:03.714Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:24:03.714Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:24:56.314Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:24:56.314Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:24:56.470Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:24:56.471Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:25:01.839Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:25:01.840Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:25:02.004Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:25:02.004Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:26:16.045Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:26:16.045Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:26:16.218Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:26:16.218Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:26:16.375Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:26:16.375Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:26:16.553Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:26:16.553Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:26:16.764Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:26:16.764Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:26:16.982Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:26:16.983Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:29:00.800Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:29:00.800Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:29:00.959Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:29:00.960Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:29:01.121Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:29:01.121Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:29:01.285Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:29:01.285Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:29:01.484Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:29:01.484Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:29:01.647Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:29:01.647Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:30:54.347Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:30:54.347Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:30:54.515Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:30:54.515Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:31:09.997Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:31:09.997Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56230' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:31:10.186Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:31:10.186Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID '56231' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:41:05.265Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:41:05.265Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:41:05.422Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:41:05.423Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:41:05.634Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:41:05.634Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_1' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-06T08:41:05.791Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-06T08:41:05.791Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CA_2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
