2018-02-01T06:13:08.880Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-01T06:13:08.881Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
2018-02-01T06:14:26.445Z ERROR   HLFConnectionManager    :fabric-client()          [client-utils.js]: sendPeersProposal - Promise is rejected: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)
    at /home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/grpc/src/node/src/client.js:554:15 {}$
2018-02-01T06:14:26.445Z ERROR   HLFConnection           :invokeChainCode()        {"message":"Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n","stack":"Error: Error trying invoke business network. Error: No valid responses from any peers.\nResponse from attempted peer comms was an error: Error: chaincode error (status: 500, message: Error: Failed to add object with ID 'CO_2' as the object already exists)\n\n    at _initializeChannel.then.then.then.then.catch (/home/batista/project/project/go/src/github.com/hyperledger/ddos-defense-based-blockchain/angular-app/node_modules/composer-connector-hlfv1/lib/hlfconnection.js:916:34)\n    at <anonymous>"}$
